# Generated by Django 4.2.11 on 2024-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=50)),
                ('baslik', models.CharField(max_length=50)),
                ('aciklama', models.CharField(max_length=50)),
                ('metin', models.TextField(max_length=50)),
                ('sehir', models.CharField(max_length=50)),
                ('aktif', models.BooleanField(default=True)),
                ('yayimlanma_tarihi', models.DateField()),
                ('yaratilme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
